# Generated by Django 5.0.3 on 2024-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_rename_dayofweek_task_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day_of_week',
            field=models.CharField(max_length=20),
        ),
    ]
